
# Attempting to implement ideas from https://www.oreilly.com/library/view/managing-projects-with/0596006101/ch06.html

SHELL = /bin/sh
CC = gcc
CPP = g++
OPT = -O2
SYSLIBS = -lGL -lGLU -lGLEW -lglut


